### ISSUE TITLE
Failed to send eMail with coupons

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#42] opened 2016-10-26 22:53 UTC
When app is admin on a party on the more tab there is the option to generate coupons. But the backend fails to send this coupons to the users eMail. On my test the API was giving back a 500 wit the message "Was not able to send eMail with Coupons to fsdfsafasfsdf@trash-mail.com". locking the logs it said - was not able to connect to the configured email service. Try to get this running.

**Comment by catarata02** [comment] 2016-11-05 10:25
I tried it just now.. and did not get any failure response.. might have to do with the email address? .. does it exist? .. please more information how to reproduce, otherwise the issue is gonna be closed.

**Comment by catarata02** [comment] 2016-11-05 21:09
could not reproduce bug.. received successfully a pdf with the coupons... closing the issue

**Closed as completed by catarata02** 2016-11-05 21:09 UTC
Labels: bug
